
version: '3.8'

services:
  bot:
    image: .../avto_bot:1.0.0
    container_name: root_bot_1
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: ../.env
    depends_on:
      - db
    command: sh -c "python run_bot.py" #python application/db/database.py &&
    restart: always
    networks:
      - my_network

  db:
    image: .../postgres:latest
    container_name: root_db_1
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge


